import PropertyImage from '../../images/for-test/property.jpg';
import BrokerImage from '../../images/for-test/broker.webp';
import MapImage from '../../images/for-test/map.png';

const CardDataForSale = [
    {kind: 0, id: 1, img: PropertyImage, title: 'Bán nhà phố Thủ Đức', about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga iure molestiae nam. Sint ea rerum sunt, obcaecati maiores accusamus ex! Animi est ullam nisi nostrum velit officiis laboriosam eos in?', price: 'Giá thỏa thuận', address: '10 Khu phố 6, Linh Trung, Thủ Đức, Tp HCM', area: 100, bedroom: 2, bathroom: 2, furniture: 1, policy: 1, author_img: BrokerImage, author_id: 1, author_name: 'Đỗ Văn Bảy', update: '16/07/2024', phone: '09177777777', map: MapImage},
    {kind: 0, id: 2, img: PropertyImage, title: 'Bán nhà phố Thủ Đức', about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga iure molestiae nam. Sint ea rerum sunt, obcaecati maiores accusamus ex! Animi est ullam nisi nostrum velit officiis laboriosam eos in?', price: 'Giá thỏa thuận', address: '10 Khu phố 6, Linh Trung, Thủ Đức, Tp HCM', area: 100, bedroom: 2, bathroom: 2, furniture: 0, policy: 0, author_img: BrokerImage, author_id: 1, author_name: 'Đỗ Văn Bảy', update: '16/07/2024', phone: '09177777777', map: MapImage},
    {kind: 0, id: 3, img: PropertyImage, title: 'Bán nhà phố Thủ Đức', about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga iure molestiae nam. Sint ea rerum sunt, obcaecati maiores accusamus ex! Animi est ullam nisi nostrum velit officiis laboriosam eos in?', price: 'Giá thỏa thuận', address: '10 Khu phố 6, Linh Trung, Thủ Đức, Tp HCM', area: 100, bedroom: 2, bathroom: 2, furniture: 0, policy: 0, author_img: BrokerImage, author_id: 1, author_name: 'Đỗ Văn Bảy', update: '16/07/2024', phone: '09177777777', map: MapImage},
    {kind: 0, id: 4, img: PropertyImage, title: 'Bán nhà phố Thủ Đức', about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga iure molestiae nam. Sint ea rerum sunt, obcaecati maiores accusamus ex! Animi est ullam nisi nostrum velit officiis laboriosam eos in?', price: 'Giá thỏa thuận', address: '10 Khu phố 6, Linh Trung, Thủ Đức, Tp HCM', area: 100, bedroom: 2, bathroom: 2, furniture: 0, policy: 0, author_img: BrokerImage, author_id: 1, author_name: 'Đỗ Văn Bảy', update: '16/07/2024', phone: '09177777777', map: MapImage},
    {kind: 0, id: 5, img: PropertyImage, title: 'Bán nhà phố Thủ Đức', about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga iure molestiae nam. Sint ea rerum sunt, obcaecati maiores accusamus ex! Animi est ullam nisi nostrum velit officiis laboriosam eos in?', price: 'Giá thỏa thuận', address: '10 Khu phố 6, Linh Trung, Thủ Đức, Tp HCM', area: 100, bedroom: 2, bathroom: 2, furniture: 0, policy: 0, author_img: BrokerImage, author_id: 1, author_name: 'Đỗ Văn Bảy', update: '16/07/2024', phone: '09177777777', map: MapImage}
];
export default CardDataForSale;